apiVersion: v1
kind: ConfigMap
metadata:
  name: vidnest-config
  namespace: vidnest
data:
  NODE_ENV: production
  PORT: "5000"
  JWT_EXPIRE: 30d
  FRONTEND_URL: http://frontend-service
  VITE_API_URL: http://backend-service:5000
  MONGODB_URI: mongodb://mongo-service:27017/vidnest
