name: CI/CD Pipeline

on:
  push:
    branches: [master, develop, main]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            Frontend/package-lock.json

      # Create .env file for backend tests
      - name: Create test environment file
        working-directory: ./backend
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "JWT_SECRET=github-actions-test-secret-$(date +%s)" >> .env
          echo "JWT_EXPIRE=30d" >> .env
          echo "NODE_ENV=test" >> .env
          echo "PORT=5000" >> .env
          echo "FRONTEND_URL=http://localhost:3000" >> .env
          echo "DEBUG=false" >> .env

      # Install backend dependencies
      - name: Install backend deps
        working-directory: ./backend
        run: npm ci --silent

      # Install frontend dependencies
      - name: Install frontend deps
        working-directory: ./Frontend
        run: npm ci --silent

      # Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: npm test --silent --detectOpenHandles --forceExit

      # Run frontend tests
      - name: Run frontend tests
        working-directory: ./Frontend
        run: npm test --silent

  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: Frontend
          vercel-args: '--prod'

  deploy-prod:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: Frontend
          vercel-args: '--prod --confirm'